### ISSUE TITLE
Remind me when online again?

### ISSUE THREAD

**Issue by orschiro** [andykras/telegram-reminder-bot#1]
Dear @andykras,

What a great bot!

Thank you for your work on this. :-)

I have one question:

1. I like to send messages to myself on my Android while travelling and being offline
2. I would like to remind myself about these messages on my laptop when I am online again and the Android device was able to sync and send the scheduled messages

Thus, would it be possible to have a command such as `/rem online` instead of just time-dependent reminders? Often, I cannot tell with certainty as to when I am online again. :-)

Thanks!

Robert

**Comment by andykras** [comment]
hi Robert! 

thank you for your email. 

I'm afraid that telegram can't send deferred messages. I suggest you to use remainders included with your phone Siri/Google assistant etc. 

with best regards,
K. Andrey

Отправлено с iPhone

23.04.2017, в 16:40, Robert Orzanna <notifications@github.com> написал(а):

**Comment by orschiro** [comment]
OK, thank you! :-)
